importing relevent libraries

In [14]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import statsmodels.formula.api as sm

Loading the data file

In [3]:
data = pd.read_excel("TRUCKING.xlsx")

In [22]:
data
#x1=no of miles travelled

Driving Assignmnet   x1  n_of_deliveries  travel_time
0                   1  100                4          9.3
1                   2   50                3          4.8
2                   3  100                4          8.9
3                   4  100                2          6.5
4                   5   50                2          4.2
5                   6   80                2          6.2
6                   7   75                3          7.4
7                   8   65                4          6.0
8                   9   90                3          7.6
9                  10   90                2          6.1

modeling the data

In [5]:
x = data[['x1']]
y = data['travel_time'].values.reshape(-1,1)
reg = linear_model.LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

calculating coefficient

In [6]:
reg.coef_

array([[0.06782609]])

calculating intercept

In [7]:
reg.intercept_

array([1.27391304])

finding linear equation

In [8]:
print("The linear model is: y = {:.5} + {:.5}*Miles Traveled".format(reg.intercept_[0], reg.coef_[0][0]))

The linear model is: y = 1.2739 + 0.067826*Miles Traveled


In [16]:
x = data['x1']
y = data['travel_time']

#x2 = sm.add_constant(x)
est = sm.ols('travel_time~x1',data)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results                            
Dep. Variable:            travel_time   R-squared:                       0.664
Model:                            OLS   Adj. R-squared:                  0.622
Method:                 Least Squares   F-statistic:                     15.81
Date:                Wed, 23 Jun 2021   Prob (F-statistic):            0.00408
Time:                        20:03:01   Log-Likelihood:                -13.092
No. Observations:                  10   AIC:                             30.18
Df Residuals:                       8   BIC:                             30.79
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.2739      1.401      0.909      0.3

C:\Users\HP\Anaconda3\lib\site-packages\scipy\stats\stats.py:1450: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


In [17]:
x = data[['x1', 'n_of_deliveries']]
y = data['travel_time'].values.reshape(-1,1)
reg = linear_model.LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
reg.coef_

array([[0.0611346 , 0.92342537]])

In [19]:
reg.intercept_

array([-0.86870147])

In [20]:
print("The linear model is: y = {:.5} + {:.5}*Miles Traveled+ {:.5}*Number of Deliveries".format(reg.intercept_[0], reg.coef_[0][0],reg.coef_[0][1]))

The linear model is: y = -0.8687 + 0.061135*Miles Traveled+ 0.92343*Number of Deliveries


In [21]:
x = np.column_stack((data['x1'],data['n_of_deliveries']))
y = data['travel_time']

#x2 = sm.add_constant(x)
est = sm.ols('travel_time~x1+n_of_deliveries',data)
est2 = est.fit()
print(est2.summary())

                            OLS Regression Results                            
Dep. Variable:            travel_time   R-squared:                       0.904
Model:                            OLS   Adj. R-squared:                  0.876
Method:                 Least Squares   F-statistic:                     32.88
Date:                Wed, 23 Jun 2021   Prob (F-statistic):           0.000276
Time:                        20:06:51   Log-Likelihood:                -6.8398
No. Observations:                  10   AIC:                             19.68
Df Residuals:                       7   BIC:                             20.59
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept          -0.8687      0.952     

C:\Users\HP\Anaconda3\lib\site-packages\scipy\stats\stats.py:1450: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))
